# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'LikeTrello' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LikeTrello
  pod 'EasyPeasy'

end
