# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift_lesson1_2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift_lesson1_2
  pod 'Masonry'

  target 'swift_lesson1_2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swift_lesson1_2UITests' do
    # Pods for testing
  end

end
